version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - HF_TOKEN=${HF_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - diagnose-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - diagnose-network

networks:
  diagnose-network:
    driver: bridge
